version: '3.8'
services:
  app:
    container_name: java_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      db_url: jdbc:postgresql://db:5432/mystore
      username: postgres
      password: postgres
    depends_on:
      - db
  db:
    container_name: mystore_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mystore
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg-data: